update buildscripts

diff --git a/branches/jnguyen/global_functions b/branches/jnguyen/global_functions
--- a/branches/jnguyen/global_functions
+++ b/branches/jnguyen/global_functions
@@ -20,20 +20,29 @@ error() {
 	exit 1
 }
 
+check_variables() {
+	if [[ "x${CCS_BUILD_DIR}" = "x" ]]; then
+		printf '%s\n' 'Variable $CCS_BUILD_DIR not defined.'
+		exit 1
+	elif [[ "x${CCS_SOURCE_DIR}" = "x" ]]; then
+		printf '%s\n' 'Variable $CCS_SOURCE_DIR not defined.'
+		exit 1
+	fi
+}
 setup_rpmbuild_tree() {
 	msg "Setting up a clean rpmbuild tree ..."
-	rm -rf "${RPM_BUILD_DIR}"
+	rm -rf "${CCS_BUILD_DIR}"
 	rpmdev-setuptree || error "ERROR: rpmbuild tree setup failed"
-	rm -rf "${RPM_BUILD_DIR}/SOURCES" \
-		&& ln -sf "${RPM_SOURCE_DIR}" "${RPM_BUILD_DIR}/SOURCES"
+	rm -rf "${CCS_BUILD_DIR}/SOURCES" \
+		&& ln -sf "${CCS_SOURCE_DIR}" "${CCS_BUILD_DIR}/SOURCES"
 }
 setup_source_dir() {
 	msg "Setting up source directory ..."
 	if [[ ! -d "${1}" ]]; then
 		mkdir "${1}" || error "ERROR: directory creation failed"
 	fi
-	rm -rf "${RPM_BUILD_DIR}/SOURCES"
-	ln -sf "${1}" "${RPM_BUILD_DIR}/SOURCES" || error "ERROR: symlink creation failed"
+	rm -rf "${CCS_BUILD_DIR}/SOURCES"
+	ln -sf "${1}" "${CCS_BUILD_DIR}/SOURCES" || error "ERROR: symlink creation failed"
 }	
 download_file() {
 	if [[ ! -f "${2}" ]]; then
